swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger API Doc
  contact:
    email: chameera.lakshitha212@gmail.com
host: 18.223.116.151:8000
basePath: /
tags:
  - name: Customer Service
    description: Operations related to customer service
  - name: Note Service
    description: Operations related to note service

schemes:
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

paths:
  'customer':
    post:
      tags:
        - Customer Service
      summary: Create customer
      description: Creating a new customer account
      operationId: createCustomer
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              firstName:
                type: string
                required: true
                description: First name must be longer than 2 characters.
              lastName:
                type: string
              email:
                type: string
                required: true
              password:
                type: string
                required: true
                description: Password must be longer than 3 characters.
              contactNumber:
                type: string                
              isActive:
                type: boolean
            example:
              firstName: Dummy
              lastName: Dummy
              email: dummy@gmail.com 
              password: dummy
              contactNumber: 123456789
              isActive: true
      responses:
        '201':
          description: successful operation
          schema:
            type: object
        '400':
          description: error message
definitions:
  Customer:
    type: object
    properties:
      _id:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      contactNumber:
        type: string
      isActive:
        type: boolean
    xml:
      name: Customer
  Note:
    type: object
    properties:
      _id:
        type: string
      title:
        type: string
      description:
        type: string
      customerId:
        type: string
      isActive:
        type: boolean
    xml:
      name: Note
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
